In [1]:
import pandas as pd
import re
import html

df = pd.read_excel("AUTOMOTIVE_INDUSTRY_AUG-SEP_2026.xlsx")
OUTPUT_PATH = "step1_weak_filter.xlsx"

In [2]:
df.shape

(86034, 77)

In [3]:
df = df[["source", "content", "domain", "topics", "sentiment", "sentiment class"]]

In [4]:
print(df.shape)
print(df.columns.tolist())

(86034, 6)
['source', 'content', 'domain', 'topics', 'sentiment', 'sentiment class']

In [5]:
df.isna().sum()

source               0
content            156
domain               0
topics             432
sentiment          428
sentiment class      0
dtype: int64

In [6]:
pd.set_option("display.max_colwidth", 300)

df["content"].sample(20, random_state=42)

71476    24, 5'10", blonde, 200 lbs, beard that makes me look a little older than I am — and I promise I'm not ugly. I send face pics without the games.  I'm looking for a girl who's skinny, any hair color, who actually likes to talk dirty and mean it. I want a sext partner who can keep up when I get exp...
14044    My partner (M36) and I (M33) are buying a new mattress and I found a brand I really like. Now we're stuck on size.Our bedroom can *physically* fit either a queen or king, but honestly neither is ideal for the proportions of the room. It was very clearly built with a full-size bed in mind.If you ...
30376    There is no one answer to this because at that price point, most bikes from major brands are similar specs-wise. Your next priority is the type of bike: endurance, aero, climb, gravel, cyclocross. Since you're a beginner, focus on these three:Aero (Race geometry) - Most aggressive position, shor...
43366                                                                                                                                                                    You may have gained 30lbs but going from these pics, you also gained a sparkle in your eye and your smile is even nicer than it was before!
34892    Appetite suppression to the point you're having to force yourself to eat would be classified as an unwanted side effect. If that's where you are, either your dose is too high or you're someone who is very sensitive to the medicine in a not-good kind of way.2 lbs a week is more than 1% of your bo...
68695    PERTANDINGAN KARUM TERTUTUP TAMAN RIA 🎱🏆 Telah berlangsung Pertandingan Karum Tertutup di Taman Ria yang menghimpunkan para peserta dalam suasana meriah,santai dan penuh semangat kesukanan. Dirasmikan oleh Ketua PKR Cabang Jerantut merangkap Penyelaras DUN Damak,Prof.Dato'Dr. Hassan Basri, sebag...
69161    RESCUE ONLY ‼️‼️🆘 Although rescue only, this dog can still go from a rescue to the right adopter! If you are interested in adopting this dog, DM OP or BanditY77 so that you can fill out an adoption form immediately! Please help! Available for adoption (in or out of state or Canada), rescue, or l...
72310                                                                                                                                                                                                                                                              You're beautiful but black hair suits you better.
57604                                                                                          Honestly, I have weights all over the place in my room, about 400 lbs worth, and it is pretty cluttered, so I just put them under my bed lol, but I mostly work out in my company's gym since zero people go in there
43045    🚨 PLEASE SHARE — HELP LOCATE 17-YEAR-OLD TRISTEN COLEMAN 🚨Authorities are seeking the public's help in locating Tristen Coleman, a 17-year-old who was last seen in Port Richey, Florida, USA.According to the Pasco Sheriff's Office, Tristen was last seen during the early morning hours of September...
30153    ⚒A footprint of a 55-million-year-old predator has been discovered in volcanic mud on Antarctica. The fossil was collected from the Fossil Hill Formation on the Fildes Peninsula of King George Island. It represents the oldest known footprint of a mammal on Antarctica, as well as the earliest evi...
24013    Don't be discouraged.  I can guarantee you that there aren't many, if any, men benching 225 lbs without training for it.  Maybe they did some other workouts or work a physical job that uses a lot of chest, but it's not something that realistically happens.Eat enough calories to grow, eat fairly ...
65387    Electronics plant owners, stop gambling on mat specs‼️Most people buy a mat, throw it on the floor, hope for the best🙈That's not how it works: 💥 10kV mat on a 30kV board... not enough insulation 🌧️ Wet or uneven floor... mat won't last 📋 Failed audit... whole project delayedThat's where we come ...
21033    Geng Kuantan, KITA FM nak sampai!  Kali ni KITA FM disatukan oleh AEON Credit dan kita bakal singgah di 📍 Menara 188, Kuantan, Pahang pada 2 September, mulai jam 8.30 malam hingga 11 malam! Sambil layan concert tu, bolehlah bawa helmet lama untuk tukar kepada helmet baharu di booth AEON Credit. ...
63319    ‼️ FREE Functional Fat Loss Masterclass for Women on September 21st at 7pm EST — comment MASTERCLASS to register! ‼️⁣⁣I was working out almost every day, eating "clean," doing everything the fitness world told me to do. And somehow I was just getting MORE inflamed the harder I pushed.⁣⁣Turns out...
50718    We have no RB cover and both LBs are injury prone. We have no players who are good in the air at all and 100% are going to lose a lot of goals because of that.. what 10, maybe? We have one injury prone defender with any pace at all. That wasn't necessary. Especially when you look at Vuskovic's p...
84262    PUSAT PENGURUSAN TRAFIK LLMKEMASKINI TRAFIK🗓️Tarikh : 21 September 2026 (Isnin)⏰Masa : 5.06pm🌤️Cuaca : Hujan di beberapa lokasiSTATUS TRAFIK DI LEBUHRAYA SELURUH NEGARA🛣️🛣️🛣️Trafik bergerak perlahan di lokasi-lokasi sepertimana berikut :🚗 🛵 🚕 🏍️ 🚙 🚌 🚚🚐🚛🔹LEBUHRAYA UTARA-SELATAN (LUS)@E1➡️Arah Uta...
68594    Hari ini perhatian tertumpu kepada MHD. Dengan pendekatan kreatif yang tersendiri, muzik yang penuh tenaga serta kebolehannya menggabungkan rentak Afrika dengan hip-hop moden, dia telah menjadi antara nama yang paling dikenali dalam arena muzik Perancis sejak beberapa tahun kebelakangan ini. Ide...
632      Poplar Bluff Trailer released a new guide detailing recommended trailer sizes, types, and features for hauling golf carts - covering aluminum utility, enclosed cargo, and tilt trailers in the 10' to 14' range.  -- Poplar Bluff Trailer's latest guide reveals recommended trailer sizes, types, and ...
66057    🏡 AVAILABLE FOR ADOPTION, FOSTER, OR RESCUE🚗 OUT OF STATE OR CANADIAN ADOPTION IS POSSIBLE — cost is typically around $600 USD (give or take). The fee includes transport, boarding, full medical, spay/neuter, and a health certificate.We are a volunteer network dedicated to helping at-risk dogs. W...
Name: content, dtype: object

In [7]:
FILE_PATH = "AUTOMOTIVE_INDUSTRY_AUG-SEP_2026.xlsx"

print(FILE_PATH)

AUTOMOTIVE_INDUSTRY_AUG-SEP_2026.xlsx

In [8]:
import pandas as pd

print(pd.__version__)

2.2.3

In [9]:
df = pd.read_excel(
    "AUTOMOTIVE_INDUSTRY_AUG-SEP_2026.xlsx",
    usecols="D,G,K,M,N,S,T"
)

print(df.shape)
print(df.columns.tolist())

(86034, 7)
['source', 'content', 'url', 'domain', 'topics', 'sentiment', 'sentiment class']

In [10]:
df = pd.read_excel(
    FILE_PATH,
    usecols="D,G,K,M,N,S,T"
)

print("Rows:", len(df))
print("Columns:", df.columns.tolist())

df.head()

Rows: 86034
Columns: ['source', 'content', 'url', 'domain', 'topics', 'sentiment', 'sentiment class']

,source,content,url,domain,topics,sentiment,sentiment class
0,Facebook Pages,"🚨 SUMNER COUNTY BOOKING REPORTSumner County Jail records show a booking for TIBBS, CORLEONE A.📅 Booking Date: 08/25/2026 15:19🎂 Age: 20⚧ Sex: MALE📏 Height/Weight: 5'8 / 160 lbs📋 Listed Charge / Bond Information:• VIOLATION OF PROBATION — $7,500📌 Charge Context:Probation-related charges usually i...",https://www.facebook.com/766412409889283_122166447302987464,www.facebook.com,"Sumner County Jail,booking,TIBBS,CORLEONE A.,VIOLATION OF PROBATION,court-ordered probation requirements,Sumner County Inmate Alerts,arrest,conviction,charges,bond,court dates,public records,local news",0.0,neutral
1,Youtube,Nikmati koleksi lagu Melayu klasik tahun 70'an yang penuh makna dan kenangan.(00:00) Cinta Dalam Setia(04:28) Di Taman Cinta(09:12) Jangan Pergi Sayang(14:09) Kasih Di Ujung Hati(19:11) Kasih Yang Kurindukan(23:39) Menanti Cinta Lama(28:02) Rindu Di Tepi Pantai(31:56) Rindu Membawa Cinta(36:11) ...,https://www.youtube.com/watch?v=uNtD3h18aQE,www.youtube.com,"Lagu Melayu Nostalgia,Album Musik Melayu Klasik,lagu Melayu klasik,tahun 70'an,cinta,romantisme,musik klasik,kerinduan,kenangan,lagu cinta",1.0,positive
2,Facebook Pages,"My client lost 15 lbs in 3 months at 57 years old while navigating menopause.She was eating healthy and working out, but the scale wouldn't budge.Until we helped her change these 2 things.She's a project manager. Busy schedule. Active lifestyle - she rides horses, she's running around all day tr...",https://www.facebook.com/110648045091736_10246091652684862,www.facebook.com,"weight loss,menopause,active lifestyle,personalized nutrition,calories and macros,workouts,life coaching,project manager,healthy eating,lifestyle change,tailored advice",1.0,positive
3,Facebook Pages,"KENDALKendal adalah kabupaten yang terletak di pesisir utara (Pantura) Provinsi Jawa Tengah, berbatasan dengan Laut Jawa di utara, Kabupaten Semarang di timur, Kabupaten Temanggung di selatan, serta Kabupaten Batang di barat. Wilayah ini dilintasi oleh aliran Sungai Kendal yang menjadi nadi kehi...",https://www.facebook.com/300835164076564_1663891442412940,www.facebook.com,"Kabupaten Kendal,Jawa Tengah,Laut Jawa,Sungai Kendal,kota asem,kota santri,Kawasan Industri Kendal,PP Al-Ihsan,PP Nurul Jihad,sejarah kepahlawanan,Ki Ageng Bahureksa,Sultan Agung,Kesultanan Mataram,Daghregister Batavia,Babad Tanah Jawi,Peta Kolonial,toponomi,etimologi",0.0,neutral
4,Instagram Public,"🚨 Now Hiring: Production Associate – 2nd Shift &amp; Enjoy 3-Day Weekends! 🚨Earn $19/hr working Monday-Thursday, 2:30pm-12:30am or 3:00pm-1:00am in Oshkosh. This seasonal role offers a great schedule and a fun, fast-paced environment!✨ Key Requirements: ✅ High school diploma or equivalent ✅ Atte...",https://www.instagram.com/p/DcexHDsjAWU/,www.instagram.com,"Production Associate,3-Day Weekends,2nd Shift,19/hr,Oshkosh,seasonal role,fun environment,high school diploma,organizational skills,military time,measuring and cutting,operating machinery,Fit Staff,Job Opportunity,#NowHiring,#ProductionJobs,#JoinOurTeam",1.0,positive

In [11]:
def clean_text(x):
    if pd.isna(x):
        return ""
    x = html.unescape(str(x))
    x = re.sub(r"https?://\\S+", " ", x)
    x = re.sub(r"\\s+", " ", x)
    return x.strip().lower()

df["content_clean"] = df["content"].map(clean_text)
df["topics_clean"] = df["topics"].map(clean_text)

In [12]:
print(df.head())
print(df.columns)

             source  \
0    Facebook Pages
1           Youtube
2    Facebook Pages
3    Facebook Pages
4  Instagram Public

                                                                                                                                                                                                                                                                                                       content  \
0  🚨 SUMNER COUNTY BOOKING REPORTSumner County Jail records show a booking for TIBBS, CORLEONE A.📅 Booking Date: 08/25/2026 15:19🎂 Age: 20⚧ Sex: MALE📏 Height/Weight: 5'8 / 160 lbs📋 Listed Charge / Bond Information:• VIOLATION OF PROBATION — $7,500📌 Charge Context:Probation-related charges usually i...
1  Nikmati koleksi lagu Melayu klasik tahun 70'an yang penuh makna dan kenangan.(00:00) Cinta Dalam Setia(04:28) Di Taman Cinta(09:12) Jangan Pergi Sayang(14:09) Kasih Di Ujung Hati(19:11) Kasih Yang Kurindukan(23:39) Menanti Cinta Lama(28:02) Rindu Di Tepi Pantai(31:56) Rindu Membawa Cinta(36:11) ...
2  My client lost 15 lbs in 3 months at 57 years old while navigating menopause.She was eating healthy and working out, but the scale wouldn't budge.Until we helped her change these 2 things.She's a project manager. Busy schedule. Active lifestyle - she rides horses, she's running around all day tr...
3  KENDALKendal adalah kabupaten yang terletak di pesisir utara (Pantura) Provinsi Jawa Tengah, berbatasan dengan Laut Jawa di utara, Kabupaten Semarang di timur, Kabupaten Temanggung di selatan, serta Kabupaten Batang di barat. Wilayah ini dilintasi oleh aliran Sungai Kendal yang menjadi nadi kehi...
4  🚨 Now Hiring: Production Associate – 2nd Shift &amp; Enjoy 3-Day Weekends! 🚨Earn $19/hr working Monday-Thursday, 2:30pm-12:30am or 3:00pm-1:00am in Oshkosh. This seasonal role offers a great schedule and a fun, fast-paced environment!✨ Key Requirements: ✅ High school diploma or equivalent ✅ Atte...

                                                           url  \
0  https://www.facebook.com/766412409889283_122166447302987464
1                  https://www.youtube.com/watch?v=uNtD3h18aQE
2   https://www.facebook.com/110648045091736_10246091652684862
3    https://www.facebook.com/300835164076564_1663891442412940
4                     https://www.instagram.com/p/DcexHDsjAWU/

              domain  \
0   www.facebook.com
1    www.youtube.com
2   www.facebook.com
3   www.facebook.com
4  www.instagram.com

                                                                                                                                                                                                                                                                         topics  \
0                                                                     Sumner County Jail,booking,TIBBS,CORLEONE A.,VIOLATION OF PROBATION,court-ordered probation requirements,Sumner County Inmate Alerts,arrest,conviction,charges,bond,court dates,public records,local news
1                                                                                                                                    Lagu Melayu Nostalgia,Album Musik Melayu Klasik,lagu Melayu klasik,tahun 70'an,cinta,romantisme,musik klasik,kerinduan,kenangan,lagu cinta
2                                                                                                      weight loss,menopause,active lifestyle,personalized nutrition,calories and macros,workouts,life coaching,project manager,healthy eating,lifestyle change,tailored advice
3  Kabupaten Kendal,Jawa Tengah,Laut Jawa,Sungai Kendal,kota asem,kota santri,Kawasan Industri Kendal,PP Al-Ihsan,PP Nurul Jihad,sejarah kepahlawanan,Ki Ageng Bahureksa,Sultan Agung,Kesultanan Mataram,Daghregister Batavia,Babad Tanah Jawi,Peta Kolonial,toponomi,etimologi
4                 Production Associate,3-Day Weekends,2nd Shift,19/hr,Oshkosh,seasonal role,fun environment,high school diploma,organizational skills,military time,measuring and cutting,operating machinery,Fit Staff,Job Opportunity,#NowHiring,#ProductionJobs,#JoinOurTeam

   sentiment sentiment class  \
0        0.0         neutral
1        1.0        positive
2        1.0        positive
3        0.0         neutral
4        1.0        positive

                                                                                                                                                                                                                                                                                                 content_clean  \
0  🚨 sumner county booking reportsumner county jail records show a booking for tibbs, corleone a.📅 booking date: 08/25/2026 15:19🎂 age: 20⚧ sex: male📏 height/weight: 5'8 / 160 lbs📋 listed charge / bond information:• violation of probation — $7,500📌 charge context:probation-related charges usually i...
1  nikmati koleksi lagu melayu klasik tahun 70'an yang penuh makna dan kenangan.(00:00) cinta dalam setia(04:28) di taman cinta(09:12) jangan pergi sayang(14:09) kasih di ujung hati(19:11) kasih yang kurindukan(23:39) menanti cinta lama(28:02) rindu di tepi pantai(31:56) rindu membawa cinta(36:11) ...
2  my client lost 15 lbs in 3 months at 57 years old while navigating menopause.she was eating healthy and working out, but the scale wouldn't budge.until we helped her change these 2 things.she's a project manager. busy schedule. active lifestyle - she rides horses, she's running around all day tr...
3  kendalkendal adalah kabupaten yang terletak di pesisir utara (pantura) provinsi jawa tengah, berbatasan dengan laut jawa di utara, kabupaten semarang di timur, kabupaten temanggung di selatan, serta kabupaten batang di barat. wilayah ini dilintasi oleh aliran sungai kendal yang menjadi nadi kehi...
4  🚨 now hiring: production associate – 2nd shift & enjoy 3-day weekends! 🚨earn $19/hr working monday-thursday, 2:30pm-12:30am or 3:00pm-1:00am in oshkosh. this seasonal role offers a great schedule and a fun, fast-paced environment!✨ key requirements: ✅ high school diploma or equivalent ✅ attentio...

                                                                                                                                                                                                                                                                   topics_clean
0                                                                     sumner county jail,booking,tibbs,corleone a.,violation of probation,court-ordered probation requirements,sumner county inmate alerts,arrest,conviction,charges,bond,court dates,public records,local news
1                                                                                                                                    lagu melayu nostalgia,album musik melayu klasik,lagu melayu klasik,tahun 70'an,cinta,romantisme,musik klasik,kerinduan,kenangan,lagu cinta
2                                                                                                      weight loss,menopause,active lifestyle,personalized nutrition,calories and macros,workouts,life coaching,project manager,healthy eating,lifestyle change,tailored advice
3  kabupaten kendal,jawa tengah,laut jawa,sungai kendal,kota asem,kota santri,kawasan industri kendal,pp al-ihsan,pp nurul jihad,sejarah kepahlawanan,ki ageng bahureksa,sultan agung,kesultanan mataram,daghregister batavia,babad tanah jawi,peta kolonial,toponomi,etimologi
4                 production associate,3-day weekends,2nd shift,19/hr,oshkosh,seasonal role,fun environment,high school diploma,organizational skills,military time,measuring and cutting,operating machinery,fit staff,job opportunity,#nowhiring,#productionjobs,#joinourteam
Index(['source', 'content', 'url', 'domain', 'topics', 'sentiment',
       'sentiment class', 'content_clean', 'topics_clean'],
      dtype='object')

Now, we are seperating between highly irrelevant posts such as reddit weird novels & fanfiction and many other contents that have nothing to do to relate with cars

# CELL 6

below is what the filter basics are

In [13]:
BRANDS = """
toyota honda proton perodua nissan mazda hyundai kia ford byd tesla chery jaecoo omoda
geely gwm haval mitsubishi volkswagen vw bmw mercedes benz suzuki isuzu subaru lexus audi
porsche volvo peugeot renault jeep chevrolet skoda lotus denza zeekr leapmotor xpeng neta
jetour kaiyi maxus mg
""".split()


MODELS = [
    "hilux", "vios", "camry", "corolla", "yaris", "innova", "fortuner",
    "alphard", "vellfire", "myvi", "axia", "bezza", "ativa", "aruz", "alza",
    "saga", "persona", "iriz", "exora", "x50", "x70", "x90", "civic",
    "accord", "hr-v", "cr-v", "ranger", "mustang", "cybertruck", "jimny",
    "atto 3", "model 3", "model y", "e.mas"
]


CAR_TERMS = [
    # General automotive
    "car", "cars", "vehicle", "vehicles", "automotive", "automobile", "auto",
    "motor vehicle", "motorcar",

    # Vehicle types
    "sedan", "suv", "mpv", "hatchback", "pickup", "pickup truck", "truck",
    "4wd", "4x4", "awd", "2wd", "coupe", "convertible", "wagon", "estate",
    "crossover", "cuv", "van", "minivan", "lcv", "commercial vehicle",

    # EV / powertrain
    "ev", "evs", "electric vehicle", "electric car", "hybrid", "phev",
    "hev", "bev", "ice", "internal combustion", "fuel", "charging",
    "charger", "charging station", "fast charging", "supercharger",
    "battery",

    # Mechanical / parts
    "engine", "motor", "gear", "gearbox", "transmission", "automatic",
    "manual", "horsepower", "torque", "turbo", "turbocharger",
    "supercharger", "brake", "brakes", "braking", "steering",
    "steering wheel", "suspension", "shock absorber", "absorber",
    "tyre", "tyres", "tire", "tires", "wheel", "wheels", "rim", "rims",
    "alloy wheels", "bumper", "bonnet", "hood", "boot", "trunk", "door",
    "doors", "windscreen", "windshield", "window", "headlight", "taillight",
    "indicator", "airbag", "seatbelt", "seat belt", "sunroof", "odometer",
    "mileage", "speedometer", "dashboard",

    # Ownership / usage
    "road tax", "car insurance", "registration", "number plate",
    "license plate", "driving license", "car loan", "car financing",
    "installment", "maintenance", "servicing", "service", "repair",
    "workshop", "spare parts", "parts", "replacement", "warranty",
    "waranti",

    # Automotive business
    "dealership", "dealer", "showroom", "test drive", "service centre",
    "service center", "booking", "delivery", "launch", "launched",
    "facelift", "new model", "new variant", "variant", "spec", "specs",
    "specification", "features", "promotion", "promo", "discount",
    "rebate", "deposit", "downpayment", "down payment", "trade in",
    "trade-in", "used car", "second hand", "pre owned", "pre-owned",
    "recon"
]


# ---------------------------------------------------------
# MALAY / MANGlish automotive terms
# Single words are intentionally broad for Step 1.
# ---------------------------------------------------------

MALAY_AUTO_TERMS = [

    # Vehicles / people
    "kereta", "kenderaan", "mobil", "automotif", "motosikal", "motor",
    "motorsikal", "van", "lori", "bas", "teksi", "pemandu", "memandu",
    "pandu", "pemanduan", "penumpang", "pemilik", "pemilikan",

    # Mechanical / parts
    "enjin", "gear", "gearbox", "transmisi", "tayar", "brek", "stereng",
    "roda", "rim", "bateri", "bonet", "bumper", "cermin", "tingkap",
    "lampu", "hon", "ekzos", "radiator", "absorber", "suspensi", "clutch",
    "minyak", "petrol", "diesel", "cecair", "pelincir", "wiper", "fius",
    "sensor", "airbag", "belt",

    # Buying / selling / ownership
    "beli", "jual", "jualan", "sewa", "sewaan", "pinjam", "pinjaman",
    "ansuran", "deposit", "bayaran", "harga", "murah", "mahal", "diskaun",
    "promosi", "tawaran", "rebat", "waranti", "insurans", "geran", "lesen",
    "pendaftaran", "nombor", "plat",

    # Maintenance / repair
    "servis", "service", "bengkel", "baiki", "baikpulih", "pembaikan",
    "rosak", "kerosakan", "mekanik", "mekanikal", "penyelenggaraan",
    "tukar", "ganti", "alat", "spare", "part",

    # Roads / driving
    "jalan", "lebuhraya", "lebuh", "raya", "trafik", "kesesakan", "sesak",
    "jem", "tol", "lorong", "simpang", "bulatan", "isyarat", "parkir",
    "parking", "perjalanan",

    # Accidents / road events
    "kemalangan", "langgar", "terlanggar", "rempuh", "terbabas", "terbalik",
    "banjir", "lubang", "permukaan",

    # Fuel / energy
    "cas", "mengecas", "pengecas", "elektrik", "hibrid",

    # Automotive business
    "dealer", "penjual", "pengedar", "kedai", "showroom", "pameran",
    "wakil", "pusat", "cawangan", "tempahan", "tempah", "booking",
    "penghantaran", "pelancaran", "dilancar",

    # Vehicle characteristics
    "baru", "terpakai", "lama", "recon", "secondhand", "selesa", "laju",
    "perlahan", "kuat", "lemah", "berat", "ringan", "besar", "kecil",
    "tinggi", "rendah", "jimat", "boros", "selamat", "bahaya", "cantik",
    "hodoh", "mewah",

    # General automotive discussion
    "model", "varian", "spesifikasi", "spec", "ciri", "prestasi", "kualiti",
    "reka", "bentuk", "dalaman", "luaran", "interior", "eksterior", "ruang",
    "tempat", "duduk", "pengalaman", "owner"
]


# ============================================================
# AUTOMOTIVE URL TERMS
# ============================================================

URL_AUTO_TERMS = [

    # Major brands
    "toyota", "honda", "proton", "perodua", "nissan", "mazda", "hyundai",
    "kia", "ford", "byd", "tesla", "chery", "jaecoo", "omoda", "geely",
    "gwm", "haval", "mitsubishi", "volkswagen", "bmw", "mercedes", "suzuki",
    "isuzu", "subaru", "lexus", "audi", "porsche", "volvo", "peugeot",
    "renault", "jeep", "chevrolet", "skoda", "lotus", "denza", "zeekr",
    "leapmotor", "xpeng", "neta", "jetour", "kaiyi", "maxus", "mg",

    # General automotive URL terms
    "car", "cars", "vehicle", "vehicles", "automotive", "auto", "motor",
    "motoring", "carnews", "carnewsasia", "carreview", "carreviews",
    "carprice", "carprices", "carbuyer", "carbuyers", "carinsurance",
    "carloan", "carloans", "carrepair", "carrepairs", "vehiclerepair",
    "vehicle-repair", "autorepair", "auto-repair", "workshop",
    "servicecentre", "service-center", "dealership", "dealer", "showroom",
    "testdrive", "test-drive", "motors", "motorist", "motorists", "driving",
    "driver", "drivers", "road", "roads", "highway", "highways", "traffic",
    "automobile", "automobiles", "sedan", "suv", "mpv", "hatchback",
    "pickup", "pickuptruck", "pickup-truck", "truck", "ev", "electricvehicle",
    "electric-vehicle", "hybrid", "phev"
]


# IMPORTANT:
# Do NOT use build_regex() here.
# URLs can contain words without normal word boundaries,
# e.g. "HondaElement" contains "Honda".
URL_AUTO_RX = re.compile(
    "|".join(
        re.escape(term.lower())
        for term in sorted(set(URL_AUTO_TERMS), key=len, reverse=True)
    ),
    re.IGNORECASE
)


# ---------------------------------------------------------
# Broad context terms
# Step 1 is intentionally weak: noise is OK.
# ---------------------------------------------------------

CONTEXT_TERMS = [

    # Roads / traffic
    "road", "roads", "highway", "highways", "expressway", "expressways",
    "motorway", "traffic", "traffic jam", "jam", "congestion", "toll",
    "tol", "parking", "parking lot", "junction", "intersection",
    "roundabout", "lane", "lanes", "road condition", "pothole", "potholes",

    # Driving
    "drive", "driving", "driver", "drivers", "motorist", "motorists",
    "commute", "commuting", "journey", "trip", "ride", "riding",

    # Incidents
    "accident", "crash", "collision", "hit", "rear ended", "rear-ended",
    "overturned", "rollover", "breakdown", "stuck", "stranded",

    # Money / purchase context
    "price", "pricing", "harga", "cost", "expensive", "cheap", "affordable",
    "loan", "installment", "monthly payment", "deposit", "downpayment",

    # Fuel
    "fuel", "petrol", "diesel", "gas", "gasoline", "fuel price",
    "petrol price",

    # Malaysian road context
    "lebuhraya", "jalan raya", "jalan", "kemalangan", "kesesakan",
    "trafik", "tol", "pemanduan", "memandu"
]


# ---------------------------------------------------------
# Chinese / CJK automotive terms
# ---------------------------------------------------------

CJK_TERMS = [
    "车", "汽车", "车辆", "丰田", "本田", "宝腾", "比亚迪", "特斯拉",
    "奇瑞", "日产", "马自达", "现代", "起亚", "福特", "吉利", "宝马",
    "奔驰", "大众", "沃尔沃", "保时捷", "雷克萨斯", "路虎", "捷豹",
    "轮胎", "刹车", "引擎", "发动机", "变速箱", "汽油", "柴油",
    "电动车", "混合动力", "充电", "驾驶", "司机", "交通", "高速公路",
    "停车", "车祸", "价格", "贷款", "保险", "维修"
]


# ---------------------------------------------------------
# Build regex
# ---------------------------------------------------------

def build_regex(terms):
    parts = sorted(
        {re.escape(t.lower()) for t in terms},
        key=len,
        reverse=True
    )

    return re.compile(
        r"(?<!\w)(?:" + "|".join(parts) + r")(?!\w)",
        re.IGNORECASE
    )


# ---------------------------------------------------------
# Combine all automotive-related terms
# ---------------------------------------------------------

ALL_AUTO_TERMS = (
    BRANDS
    + MODELS
    + CAR_TERMS
    + MALAY_AUTO_TERMS
)

CAR_RX = build_regex(ALL_AUTO_TERMS)
CONTEXT_RX = build_regex(CONTEXT_TERMS)


# Chinese does not reliably use spaces,
# so don't use word boundaries.
CJK_RX = re.compile(
    "|".join(re.escape(t) for t in CJK_TERMS)
)

# Cell 7 — Apply the Step 1 weak filter

In [14]:
# ============================================================
# CELL 7 — APPLY STEP 1 WEAK FILTER
# ============================================================

# Content is the main signal.
# Topics are a supporting signal to maximize recall.
# Domain is NOT used to decide automotive relevance.
#
# Step 1 is intentionally WEAK:
# We want to keep anything that MIGHT possibly be related
# to automotive, even if it turns out to be irrelevant later.

df["url_clean"] = df["url"].map(clean_text)

df["scan_text"] = (
    df["content_clean"].fillna("") + " " +
    df["topics_clean"].fillna("")
).str.strip()

df["hit_car_term"] = df["scan_text"].map(
    lambda x: bool(CAR_RX.search(x) or CJK_RX.search(x))
)

df["hit_url_auto_term"] = df["url_clean"].map(
    lambda x: bool(URL_AUTO_RX.search(x))
)

df["hit_context_term"] = df["scan_text"].map(
    lambda x: bool(CONTEXT_RX.search(x))
)

df["step1_keep"] = (
    df["hit_car_term"] |
    df["hit_url_auto_term"] |
    df["hit_context_term"]
)

In [15]:
# ============================================================
# CELL 8 — STEP 1 FILTER SUMMARY
# ============================================================

total = len(df)
kept = int(df["step1_keep"].sum())
removed = total - kept

car_only = int(
    (df["hit_car_term"] & ~df["hit_context_term"]).sum()
)

context_only = int(
    (~df["hit_car_term"] & df["hit_context_term"]).sum()
)

both = int(
    (df["hit_car_term"] & df["hit_context_term"]).sum()
)

neither = int(
    (~df["hit_car_term"] & ~df["hit_context_term"]).sum()
)

print("=" * 60)
print("STEP 1 WEAK FILTER SUMMARY")
print("=" * 60)

print(f"Total rows          : {total:,}")
print(f"Step 1 kept         : {kept:,} ({kept/total:.1%})")
print(f"Step 1 removed      : {removed:,} ({removed/total:.1%})")

print()
print("WHY ROWS WERE KEPT")
print("-" * 60)
print(f"Car/brand/model only: {car_only:,}")
print(f"Context terms only  : {context_only:,}")
print(f"Both                : {both:,}")
print(f"Neither             : {neither:,}")

print()
print("CHECK")
print("-" * 60)
print(f"Kept + Removed      : {kept + removed:,}")
print(f"Original total      : {total:,}")

if kept + removed == total:
    print("✓ Row count is consistent.")
else:
    print("⚠ Row count mismatch — investigate.")

============================================================
STEP 1 WEAK FILTER SUMMARY
============================================================
Total rows          : 86,034
Step 1 kept         : 55,005 (63.9%)
Step 1 removed      : 31,029 (36.1%)

WHY ROWS WERE KEPT
------------------------------------------------------------
Car/brand/model only: 23,236
Context terms only  : 8,785
Both                : 20,447
Neither             : 33,566

CHECK
------------------------------------------------------------
Kept + Removed      : 86,034
Original total      : 86,034
✓ Row count is consistent.

In [16]:
# ============================================================
# CELL 9 — MANUAL QUALITY CHECK
# ============================================================

pd.set_option("display.max_colwidth", 300)

# ------------------------------------------------------------
# RANDOM KEPT EXAMPLES
# ------------------------------------------------------------

print("=" * 80)
print("RANDOM KEPT EXAMPLES")
print("=" * 80)

kept_columns = [
    "source",
    "content",
    "topics",
    "hit_car_term",
    "hit_context_term"
]

display(
    df.loc[df["step1_keep"], kept_columns]
      .sample(min(30, kept), random_state=42)
)


# ------------------------------------------------------------
# RANDOM REMOVED EXAMPLES
# ------------------------------------------------------------

print()
print("=" * 80)
print("RANDOM REMOVED EXAMPLES")
print("=" * 80)

removed_columns = [
    "source",
    "content",
    "topics"
]

display(
    df.loc[~df["step1_keep"], removed_columns]
      .sample(min(30, removed), random_state=42)
)

================================================================================
RANDOM KEPT EXAMPLES
================================================================================

,source,content,topics,hit_car_term,hit_context_term
72902,Facebook Pages,"Looking back at job site workhorses always brings a real sense of nostalgia. Featured here is the Caterpillar 953D Track Loader, an incredibly versatile loading machine. Sourced from official Caterpillar specs, this rig is powered by a Cat C6.6 ACERT engine delivering 148 hp, with an operating w...","job site workhorses,nostalgia,Caterpillar 953D Track Loader,versatile loading machine,heavy digging,land clearing,material handling,automated grading systems,hydrostatic track loader,spatial awareness,foot-and-joystick control,operator grit,tame brutal terrain,senior operators,veterans,D-series ...",True,False
71413,Online News,"Difahamkan, Tasek Ipoh, Perak merekodkan bacaan tertinggi iaitu 182. Follow kami di WhatsApp Channels Telegram Instagram dan TikTok SAYS Seismik, jadi antara yang terawal untuk dapatkan berita serta artikel-artikel menarik. Keadaan kualiti udara di beberapa kawasan di Malaysia masih berada pad...","IPU,Tasek Ipoh,Perak,air quality,Kosmo!,Jabatan Alam Sekitar,Sistem Pengurusan Kualiti Alam Sekitar,MyEQMS,Tahap tidak sihat",True,False
60685,Facebook Pages,"Carey, Destiny NicoleBattery (Touch or Strike)Bail: No BondAge: 29Height: 5' 2""Weight: 200 lbsSex: FemaleSign: TaurusOrigin: USThe booking record shows one charge: an allegation of battery by touching or striking another person.No prior history is on file for this person in the record provided.T...","arraignment,battery by touching or striking,no bond,assault charge,preliminary court proceedings",True,False
54855,Instagram Public,"""I can't gain weight"" is BS. What to do instead (part 1)⁠⁠1) Track your calories - eating ""a lot"" is meaningless⁠2) Track bodyweight - 1st thing in AM, monitor trends⁠3) Pick the right surplus - aim for +.5 lbs/wk up to +1-2 lbs/wk, the more underweight you are.","gain weight,calories,bodyweight,calorie surplus,weight restoration",True,False
19189,Reddit,"getting back into the routine is the hardest part, good luck with it though! youve got this","Gym,Routine,Accountability,Lost Gains,Body Weight,Months,Fitness",True,False
49830,Instagram Public,Drive home a new GWM today with exclusive Affin Bank financing packages from as low as 2.07% p.a. equivalent flat rate.*Visit GWM Setia Alam showroom to learn more.*Terms and conditions apply.#GWM #GoWithMore #GWMMalaysia #gowithmore,"GWM,Affin Bank,financing packages,2.07% p.a.,showroom,#GWM,#GoWithMore,#GWMMalaysia,#gowithmore",True,True
26040,Facebook Pages,"""Fat Amy"" has taken up bucking and needs an owner stickier than we are!... so she is not for beginners unless you never want to be asked to ride one of your horses again lol.She is 6 yrs old, came to us out of Canada as a weanling and currently stands 16.3hh, wears a size 5 shoe and 1600 lbs (16...","Fat Amy,bucking horse,draft cross,WM Ranch's 30 year blend,PBR pick up horse,16.3hh,1600 lbs,size 5 shoe,double haltered,backed,roping,$2.365/lb,Carlin, NV",True,True
37997,Instagram Public,"🌳 STORM CLEANUP CONTINUES! 🌳Still dealing with fallen branches, damaged trees, and piles of yard debris? Let 3 Day Dumpsters help you get your property cleaned up!✅ Driveway-safe rubber-wheel dumpsters✅ Rear barn doors for easy loading✅ Up to 4,000 lbs included✅ Book online in under 5 minutes15-...","STORM CLEANUP,fallen branches,damaged trees,yard debris,dumpsters,property cleaning,driveway-safe,rear barn doors,loading,15-Yard Dumpster,18-Yard Dumpster,Oakland County,Wayne County,Novi Michigan,Tree Debris,Yard Cleanup",True,False
55546,Facebook Pages,Home Sweet Home 🏡 ❤️🐈‍⬛️🐈‍⬛️🐈‍⬛️🐈‍⬛️🐈‍⬛️🐈‍⬛️🐈‍⬛️🐈‍⬛️🐈‍⬛️I miss my beautiful and amazing mother of a daughter and our sweet Rylee girl. She turns 1 month old tomorrow. She's weighing in at 9.5 lbs. Formula change due to sensitive tummy issues and reflux. She's beautifully and wonderfully made and...,"mother,daughter,Rylee,birthday,formula change,sensitive tummy,reflux,gift from God,au natural,grandma,Jailer,Jameson,grandson,bedtime story,prayer request,Barbie,babies,prayers,peace,prosperity",True,False
74455,Reddit,"🏡 AVAILABLE FOR ADOPTION, FOSTER, OR RESCUE🚗 OUT OF STATE OR CANADIAN ADOPTION IS POSSIBLE - cost is typically around $600 USD (give or take). The fee includes transport, boarding, full medical, spay/neuter, and a health certificate.We are a volunteer network dedicated to helping at-risk dogs. W...","Germany Shepherd Mix,adoption,foster,rescue,euthanasia list,BARC Shelter,out-of-state adoption,transport,medical,spay/neuter,health certificate,pledges,local foster,leases,barks,volunteer network,David Posie",True,True
78686,Facebook Pages,"Pagi yang bermula seperti biasa… seawal jam 6.30 pagi, seorang ayah melangkah keluar dari rumah dengan hati penuh tanggungjawab. Di bahunya tergalas harapan sebuah keluarga—anak-anak yang menanti, isteri yang setia mendoakan. Mungkin sempat dia menoleh sebelum pergi, mungkin sempat dia tersenyum...","ayah,keluarga,rezeki,kereta,sempat,kematian,ketidakpastian,hidup,amanah,kelalaian,kasih,Allah,rahmat,kesabaran",True,True
19683,Reddit,"‼️🆘 Although rescue only, this dog can still go from a rescue to the right adopter! If you are interested in adopting this dog, DM OP or u/BanditY77 so that you can fill out an adoption form immediately! Please help! Available for adoption (in or out of state or Canada), rescue, or local foster‼...","Zucco,Euthanasia List,Rescue HOLD,BARC Shelter,Foster,Adopt,German Shepherd Mix,Rescue Only,BARC.Aid@houstontx.gov",False,False
83048,Reddit,Turns out when the D line is effective the LBs look better. Crazy.,"happy,evolved,improved,D line,LBs,effective",False,False
14416,Reddit,"First things first: safety and discretion. I don't keep your photos. You can keep or wipe the memory cards. I can shoot without memory cards at all, if you prefer. I'll also physically show you that all WiFi, Bluetooth, etc. are disabled on my camera. Finally, we can and should meet for coffee f...","safety,discretion,boudoir photoshoot,disposable camera,comfort,fun experience,sexiest woman,photography,hotel room,lighting equipment,pose list,outfits,praise,flirtier,lingering touches,bolder directions,tension,lust,photographer,laundered,relationships,discreet",True,False
37549,Reddit,"Things have been rough lately. I was informed I was losing my SSDI, because Social Security has deemed me capable of working. Spoiler alert: I'm not.I have been going through severe periods of sucidial ideation. It was particularly bad about two weeks ago, and I reached out to a friend of mine t...","SSDI,Social Security,suicidal ideation,therapist,disability,appeal",False,False
69649,Reddit,I am looking for a young woman to be my FWB. I would love to go on fun dates like the beach since it's so close by or perhaps try out some restaurants that I have been wanting to try. I prefer to keep things casual however I am willing to entertain something longer term if we fit well together. ...,"Westminster,Southern California,FWB,fun dates,beach,restaurants,casual relationship,long-term,male role of leadership,responsibility,masculine presence,submission,mutual respect,dominant,mindspace,thoughts,satisfaction,conversations,life experience,health,body type,STD free",True,False
9728,Facebook Pages,"GEMPARKAN STUDIO‼️DISAKSIKAN BUPATI &amp; WABUP SIDRAP, MELANI LANGSUNG BORONG 2 D'BOSS SEKALIGUS! Suasana di panggung D'Academy 8 langsung berubah gempar dan penuh kemeriahan! Melani dari Sidrap mencatat sejarah luar biasa dengan langsung meraih 2 D'BOSS sekaligus usai penampilannya — sebuah pe...","Melani,D'BOSS,bupati,wakil bupati,Sidrap,support,D'Academy 8,Virtual Gift,vocalist,Padi Reborn,standing ovation,supporters,community,achievement,performance,motivation",True,False
39890,Reddit,What a wierd take away... dude drove while high... he killed someone and your response is if the person he cut off and killed would have made smarter choices the high driver wouldnt have been in as much trouble....... Have you lost .. your.. mind... yep helmets are smart.. are they law.. n...,"Florida teen,DUI crash,killed biker,driving while high,laws,personal risk,public risk,driver's fault",False,True
64634,Facebook Pages,"🏡 RUMAH DI JOHOR BAHRU MASIH BELUM ADA WiFi? INI MASA PALING BERBALOI UNTUK DAFTAR UNIFI! 🔥.Kalau baru pindah rumah, baru dapat kunci atau rumah di kawasan taman sekitar Johor Bahru masih belum mempunyai apa-apa WiFi, sekarang boleh manfaatkan PROMOSI REBAT PERCUMA 6 BULAN BIL. 🎁.Bayangkan, samb...","Rumah Di Johor Bahru,WiFi,Daftar Unifi,PROMOSI REBAT PERCUMA 6 BULAN BIL,100Mbps,300Mbps,500Mbps,Smart TV,streaming,kerja dari rumah,belajar,CCTV,gaming,penggunaan harian,Johor Bahru,Skudai,Tampoi,Kempas,Setia Tropika,Taman Universiti,Taman Perling,Bukit Indah,Austin,Tebrau,Pendaftaran baru,What...",True,False
10535,Reddit,"I put on about 30-40lbs extra after having a baby and going on Zoloft for PPA in 2024/early 2025 and I've been on a weight loss journey since of calorie deficit (1200-1400 cals per day) and moderate exercise (long walks, Pilates, bike rides). I was still about 15-20 lbs away from my goal weight ...","weight loss journey,calorie deficit,moderate exercise,phentermine/topiramate,bupropion/low dose naltrexone,sleeping issues,anxiety,depression,insomnia,affordable weight loss meds,weight maintenance",True,True
82556,Reddit,You want to see the grow - except NYS entire business model works against vertical integration. When a place works with a half dozen fsrms to get to the 30k lbs of material they need a year - growing genetics they contrscted with the farm to grow - its 100% not rational. Habe you ever asked to s...,"solventless vapes,ethanol,vertical integration,NYS,30k lbs,genetics,farm,beef,eggs,transfusion",True,False
47414,Facebook Pages,"🚨🤯 ¡CASI 42 PIES DE LUJO Y SOLO $1,500 DE PAGO INICIAL! 🔥🏡🚐✨ 2022 Keystone Montana High Country 377FL ✨💵 ¡LLÉVATELA CON SOLO $1,500 DE PAGO INICIAL!💰 PRECIO CUEVAS: $45,500😱 ¡ESTO NO PARECE UNA RV… PARECE UNA CASA DE LUJO SOBRE RUEDAS! 🏡🔥Con sala amplia, cama KING, loft y muchísimo espacio, esta...","42 feet of luxury,1,500 payment,2022 Keystone Montana High Country,377FL,cama KING,loft,full kitchen,living room,bathroom,RV,luxury,Cuevas price,fifth wheel,Odessa TX",True,True
72658,Reddit,"Hey, I'm 21, from Egypt, and currently in my final year of college. I work alongside my studies and spend my free time learning things that might come in handy later. I'm also into learning new languages and picking up new skills in general.It's been about 6 months since my last relationship, an...","final year of college,languages,skills,travelling,music parties,motorcycles,sports cars,extrovert,fitness,organized,goals,long distance,support each other,grow together",True,False
10595,Instagram Public,"🌿 FRESH AIR, COMFY SPACE.Meet the Xiaomi Dehumidifier Series — designed to help keep your home feeling fresh, dry, and comfortable.✨ Xiaomi Dehumidifier Lite — BND279✨ Xiaomi Dehumidifier — BND329Say goodbye to excess humidity and hello to a more comfortable space. 💨Available at DE HOUSE.#DEHOUS...","Xiaomi Dehumidifier Series,fresh,comfy,dehumidifier,home feeling fresh,humidity,comfortable space,BND279,BND329,DE HOUSE,Koprijaya Complex,Kampong Jaya Setia,Abdul Razak Complex",True,True
60035,Reddit,"Hi everyone! I'm considering gynecomastia surgery and this would be my first surgery. I was around 105 kg (231 lbs) and I've now lost a lot of weight and I'm around 78 kg (172 lbs), but unfortunately the chest tissue hasn't gone away.At first I was really excited about the surgery and couldn't w...","gynecomastia surgery,first surgery,weight loss,chest tissue,scared,needles,anesthesia,pain,recovery,experience,comments,insults",False,False
13876,Reddit,"I just went through this. I hadn't backpacked since 96 probably.Can you use your old gear? Yeah absolutely. But if you want to save weight, you absolutely can. And I'm going to get into a little bit about how my gear failed me back in the day. Which is basically just saying I was cold if I was c...","backpacking gear,weight reduction,camping equipment,sleeping bag,sleeping pad,featuring recent technologies,current trends,wildlife safety,navigation technology,water filters,trekking poles,SPF fabrics,ultralight products,innovations in gear,personal satellite locator,merino wool,YouTube reviews",True,True
33871,Reddit,"Healthy weight loss is between 0.5- 1.5 lbs a week. You have lost 20!!! That's way above! So you need to adjust your expectations here because it will most likely slow down to normal pace. Reta always works and it also adjustes your hormonal response and metabolic pathways, it does much more tha...","healthy weight loss,0.5-1.5 lbs a week,adjust expectations,Reta,hormonal response,metabolic pathways,rapid weight loss,hanging skin,lifting weights,age,Reddit,trim,glp,sugar,inflammation,weight loss journey,body response",False,True
66299,Reddit,"Bengals D is legit. We'll see if it can be sustained, but Dexters presence in the interior allowed the LBs to fly all over the field and make plays. The secondary is still mid and Cashius Howell is promising on the edge, but he will probably lose to Tackles that can anchor better and have length...","Bengals defense,Dexters presence,interior defense,LBs mobility,secondary,Tackles,non-pass catching RBs,sustained performance",True,False
31320,Reddit,"&gt;But our ultimate goal is to lose weightFor a lot of people it really isn't. For some, the ultimate goal is health metrics, e.g., diabetes and high blood pressure reversal.For others, aesthetics is a *huge* part of the ultimate goal. I see *so* many people drop down to a normal BMI and then c...","CARDIO,weight loss,health metrics,BMI,muscle building,aesthetics,diabetes,high blood pressure,body composition,weights",True,True
36865,Reddit,"I 29f still live with my Nmom (56yrs) due to me saving money to move from my small town to the Chicago area (which I'm in mi for now). I've always dealt with random bs from my mom growing up but any time I have a bf, I swear it doubles down. My bf and I live 3hrs away from eachother so we don't ...","moving,mother,relationship,privacy,independence,stalking,boundary-setting",True,False

================================================================================
RANDOM REMOVED EXAMPLES
================================================================================

,source,content,topics
67659,Instagram Public,"JOM MAI SETIA FONTAINES CARNIVAL 🥳 Catch live performances by Ratu Rock Malaysia ELLA &amp; Mila Jirin, enjoy exciting family-friendly activities and traditional games, then top off the night with a spectacular Grand Fireworks Show! 🔥📅 19 Sept 2026 (Sat)⏰ 2pm – 10pm📍 Setia Experience Centre, Ban...","carnival,family-friendly activities,grand fireworks show,live performances,traditional games,kids colouring,batik painting,oven painting,mini treasure hunt,petting zoo,mascot appearance,lucky draw session,traditional dance performance"
79010,Reddit,"Obviously don't know what your medical reasons are, but as other comments have said, you will need to train to get some muscle definition so you dont look so soft, or ""skinny fat"". You've done lots of great hard work, but right now without very much muscle you are just bones and skin and fat, so...","lost weight,muscle definition,skinny fat,light intensity strength training,YouTube workouts,dumbbells,kettlebell"
60476,Reddit,I really thought the people adding /s on the end of their comments were being excessive😂 guess not,"wife,weight gain,marriage,comments,/s"
73513,Reddit,"Good afternoon! I hope your week has been treating you well.I'm 25, clean, disease and drug-free. I'm 5'10"", 175 lbs, and fairly well-endowed (7""+). I can host in the DMV area, near downtown DC, and I'd prefer to be safe and meet somewhere public first.To be frank, I'm completely inexperienced, ...","friendship,safe,introverted,board games,reading,museums,exhibits,cocktail parties,healthy lifestyle"
8034,Instagram Public,"THE LINES THAT BRING US HOMEWe're excited to bring you a special collaboration between SP Setia × FairyPark, exploring the invisible lines that connect us to family.From distance, to memories, to the different paths we take — some connections never truly fade.Through a series of three stories, w...","special collaboration,invisible lines,connection,family,distances,memories,three stories,travel,home"
42147,Instagram Public,"🚢 Jangan biarkan proses impor dari China terasa rumit!Dengan SAJ (Setia Abadi Jastip), kami bantu proses pembelian produk dari China hingga sampai ke Indonesia dengan lebih aman, mudah, dan transparan. Mulai dari pembelian, pembayaran, pengecekan produk, pengurusan dokumen, hingga pengiriman via...","impot,produk,China,Indonesia,pembelian,transparan,pengiriman,cargo,bisnis,hubungi SAJ,reseller"
64550,Reddit,"Welcome to Normal Nudes! This is an automated message for every post.Quick Rules: **No unsolicited health or personal grooming advice, sexual come-ons, body shaming, or any other incivility. No PMing our submitters, and do not request more photos.** This is not a hookup sub, and it's not a place...","automated message,quick rules,submission rules,flaccid,soft only,no clothing,no posing,no monetized accounts,moderators,subreddit"
62802,Online News,PETALING JAYA – Orang ramai memuji tindakan berani guru-guru Sekolah Kebangsaan (SK) Setia Alam yang bertungkus lumus berusaha memadamkan kebakaran selepas satu daripada bilik darjah di sekolah itu terbakar petang tadi. Menerusi video tular di media sosial dimuat naik pengguna Thread Papayann m...,"guru-guru,Sekolah Kebangsaan Setia Alam,berani,kebakaran,berusaha,memadamkan,pemadam api,asap tebal,makuin balas pujian,Sispaa,penghargaan,perkhidmatan,anugerah,latihan kebakaran"
15755,Instagram Public,"Juicy Spinach &amp; Cheese Stuffed Beef Roll 🥩✨ Save this recipe for your next dinner party or a special weekend treat! Melt-in-your-mouth tender beef wrapped around a rich, garlicky spinach and cheese filling. 🤤🌿📋 IngredientsFor the Beef: 800g–1kg (approx. 2 lbs) beef tenderloin, sirloin, or ri...","Spinach & Cheese Stuffed Beef Roll,dinner party,weekend treat,beef tenderloin,sirloin,ribeye,spinach,cheese filling,rosemary,oven roast,seared,sliced,rest before slicing,cooking technique"
52646,Reddit,"I am so big on mental health days for kids and I always tried to give my little ones the benefit of the doubt, and now my oldest is 16, plops her butt down in protest, and it's a lot harder to cart her up and out. With the rest of my kiddos, I've been more strict. You're going to school, and if ...","school refusal,mental health days,attendance,truancy,homecoming,prom"
19605,Reddit,I (26F) take one scoop of inositol daily before breakfast and it has helped but lately I feel like it hasn't as much. Maybe the effects are wearing off. My period has become more regularized and it did help with my mental health but honestly I feel like my hormones are wacky again and I'm const...,"GLP-1,PCOS,inositol,metformin,spirolactone,period,mental health,hormones,anxiety,weight loss,insulin resistance,testosterone levels"
78615,Facebook Pages,"Tiny Bumps You Can Feel, But Can't Pop?Your skin looks clear from a distance…But up close, you can feel tiny bumps and uneven texture?They could be closed comedones.Closed comedones can form when excess sebum and dead skin cells become trapped inside the pores.And no — squeezing harder isn't the...","closed comedones,excess sebum,dead skin cells,Squeeze,SKIN Care,SSGM9 treatment,acne,scars,pigment,dermal collagen,skin tone,skin lightening,before and after,healthier pores,Facial Treatment,Deep Cleansing"
85625,Facebook Pages,"🚨 PLEASE HELP FIND CAYLEE PARKER 🚨A public request for assistance has been issued for 16-year-old Caylee Parker, who was last seen in San Antonio, Texas, on September 19, 2026.🔎 WHAT TO KNOW:👧 Name: Caylee Parker🎂 Age: 16 years old📅 Missing Since: September 19, 2026📍 Location: 1200 block of W Lo...","Caylee Parker,missing since,September 19, 2026,San Antonio, Texas,Bexar County Sheriff's Office,help locate,missing juvenile"
76363,Reddit,"I usually play run-first when working with a low overall roster, but the passing game is both difficult and yet fairly wide open with the right reads in its current state, it just requires a lot more effort. The absolute easiest way to get the ball downfield is with play action, especially if yo...","5 star backs,run-first system,low overall roster,passing game,play action,PA QB,line play,WR,cornerback,contested catch,Dagger plays,chunk yardage,covering,speed,slot,deep post,shallow cross,mesh,jet sweeps,run game,read coverages,pocket,adjustments"
65262,Facebook Pages,"Effortless luxury, redefined. ✨Elevate your everyday wardrobe with Guy Laroche. Crafted for the modern gentleman, each piece blends French elegance, tailored comfort, and unmistakable confidence.From boardroom meetings to evening events, make a statement without saying a word. 💼🎩📍 Discover the l...","Effortless luxury,modern gentleman,French elegance,tailored comfort,confidence,boardroom meetings,evening events,statement,collection,Parkson stores,Parkson Elite Pavilion KL,1 Utama,Gurney Plaza,Pavilion Bukit Jalil,Setapak Central,Setia City Mall,Subang Parade,Sunway Pyramid,Alamanda,IOI City ..."
18991,Facebook Pages,"🍤🥑🍚 Mexican Shrimp Bowl 🤤🔥Today I made an easy and delicious Mexican Shrimp Bowl! 🍤🥑🍚 Seasoned golden shrimp, cilantro lime rice, roasted corn, fresh pico de gallo, and avocado. So simple and full of flavor! 😍❤️Ingredients:For the shrimp:* About 3 lbs peeled and deveined shrimp* Olive oil* Salt*...","Mexican Shrimp Bowl,golden shrimp,cilantro lime rice,roasted corn,pico de gallo,avocado,seasoned shrimp,recipes,cooking instructions,easy recipe,homemade dinner"
51509,Reddit,"Thank you so so much for this comment, the site doesn't have as much info about what's accepted anymore so this helps a lot.Head's up that the fee is $30 for up to 320 lbs. now.I didn't realize there might be a person there to help me offload, should I bring cash for a tip next time?","transfer station,accepted items,fee,offload help,tip"
40930,Reddit,Hard to know if it would float without knowing the thickness and thus the mass. I'm going to assume it's similar in all dimensions to the venetian canal gondolas since it has several occupants and seems to be quite long with a pole for propulsion. I'm also going to assume the ducks are analogous...,"boat,volume,mass,gold,buoyancy,float,venetian canal gondolas,Google AI,Mathematics"
77983,Reddit,"Title is pretty much the whole story. There's this bar I'm a semi-regular at, but always leave after like an hour because the chairs are so damn uncomfortable. 10 months and 60 lbs later, I can hook my feet on the bar stool rungs, and sit all the way back with room between my stomach and the e...","bar,barstools,local bar,tequila soda,60 lbs,regular furniture"
3808,Reddit,"At the beginning, I didn't really set anything in place, I just ate like I normally did but felt full so my portions were way smaller. Over the past 4 months or so, I started prioritizing protein and fiber, and I run 3x/week and do resistance training 2x/week. I started slow though, only exercis...","weight loss,255lbs,140 lbs,diet,protein,fiber,exercise,running,resistance training,portions"
61722,Reddit,"I'm a 30F and just found out I was diabetic yesterday after an ER visit and just need some support. It's really daunting for me and as much as I am trying to maintain a positive outlook, it feels like my life is over. My blood sugar was at 316 in the ER and my A1C is 11.2. I keep crying and just...","diabetic,ER visit,blood sugar,A1C,support,daunting,grandma,dad,risk factors,gym,desserts,unsolicited advice,emotions"
54810,Reddit,Yeah I'm out of shape but when I was in wrestling shape I was in the 215 lbs range even low bodyfat. I was very cognizant of the fact that I was near the weight limit of a lot of stuff like ladders if I happened to put on some weight.,"out of shape,wrestling shape,215 lbs,low bodyfat,weight limit,ladders"
41462,Reddit,😭,NaN
54156,Reddit,Well I am down 13 pounds in 14 weeks. I'm bouncing around between 201 and 203 with a goal of 185/180 but it's normal to bounce around and then lose especially when you don't have a lot to lose.,"pounds,20-25 lbs,13 pounds,14 weeks,201,203,goal,185/180,bounce around,not a lot to lose"
44243,Facebook Pages,"🙏 WHERE IS EMMA BAZAROW?Emma Bazarow, 13, was last seen on September 7, 2026, in Jacksonville, Arkansas, USA. She has been listed as a runaway juvenile, and the Jacksonville Police Department is asking the public to help locate her.CASE DETAILSName: Emma BazarowAge: 13 years oldGender: FemaleLas...","Emma Bazarow,runaway juvenile,Jacksonville Police Department,September 7, 2026,Arkansas,Safe return,Report# 26-03743,MissingInArkansas,RunawayTeen,MissingJuvenileAlert,FindEmma"
78062,Reddit,"**I started a 1400-calorie diet yesterday and I'm already struggling** I'm 25F, 5'2"" (158 cm) and 171 lbs (77.7 kg). I received a meal plan from my dietitian two days ago and started following it yesterday. The plan is around 1400 calories, and honestly, I felt **really hungry** throughout the...","1400-calorie diet,struggling,feelings of hunger,emotional overwhelm,calorie deficit,1800 calories"
16155,Reddit,Probably a bit of immaturity issues + misuse. Coleman is not built to be a boundary receiver and would find a lot more success in the slot going against LBs rather than corners. He wasn't being put in positions that allowed him to use his size to his advantage outside of the red zone,"Keon Coleman,immaturity issues,misuse,boundary receiver,slot,LBs,corners,red zone"
80762,Online News,"September 20, 2026 KUALA LUMPUR, Sept 20 — A total of 22 locations across Malaysia recorded unhealthy Air Pollutant Index (API) levels as of 9:00 am today, driven by persistent dry weather and transboundary haze originating from regional hotspots. Data from the Air Pollutant Index Management S...","unhealthy Air Pollutant Index (API),transboundary haze,dry weather,hotspots in Kalimantan,pollution levels,PEACE (pollution levels, education and awareness),Department of Environment (DOE),Environmental Quality (Amendment) Act 2024,National Haze Action Plan,APIMS portal,MyJAS EQMS application"
18790,Reddit,"🎉 💗8/31 MRS.PACMAN A659787 is SAFE with UltiMutt RSQ because a foster said YES! Please honor your pledges 🙏🏼We are so happy for this beautiful sweet girl and thankful for her amazing foster.Please honor your pledge and note "" FOR MRS. PACMAN"" so your donation goes directly to her care at:✨Dona...","foster home,forever home,light brindle Pittie,Dog-Friendly,UltiMutt RSQ,pledges,donation,adoption,transport,Houston, TX"
81935,Reddit,"I use stone and lbs, I'm just used to it. I'm 38 so not super old. The people I know who used kg are gym goers lol.","km,miles,stone,lbs,kg,gym goers"

In [17]:
print(df.columns.tolist())

['source', 'content', 'url', 'domain', 'topics', 'sentiment', 'sentiment class', 'content_clean', 'topics_clean', 'url_clean', 'scan_text', 'hit_car_term', 'hit_url_auto_term', 'hit_context_term', 'step1_keep']

In [18]:
print("COLUMNS ACTUALLY IN df:")
for i, col in enumerate(df.columns):
    print(i, repr(col))

COLUMNS ACTUALLY IN df:
0 'source'
1 'content'
2 'url'
3 'domain'
4 'topics'
5 'sentiment'
6 'sentiment class'
7 'content_clean'
8 'topics_clean'
9 'url_clean'
10 'scan_text'
11 'hit_car_term'
12 'hit_url_auto_term'
13 'hit_context_term'
14 'step1_keep'

In [19]:
# Check the EXACT names pandas gave the extra columns

extra_columns = pd.read_excel(
    FILE_PATH,
    usecols="J,AW:AZ,BB",
    nrows=0
)

print("Exact column names:")
for i, col in enumerate(extra_columns.columns):
    print(i, repr(col))

Exact column names:
0 'language'
1 'no. of comments'
2 'no. of likes'
3 'no. of shares'
4 'no. of views'
5 'Engagements/social shares'

In [20]:
# ============================================================
# CELL 10 — SAVE STEP 1 OUTPUT + REMOVED ROWS
# ============================================================

# Read the additional columns from the original Excel file
extra = pd.read_excel(
    FILE_PATH,
    usecols="H,J,AW:AZ,BB"
)

print("Original headers found:")
print(extra.columns.tolist())

# Rename them to consistent names for our output
extra.columns = [
    "date (UTC)",
    "language",
    "no_of_comments",
    "no_of_likes",
    "no_of_shares",
    "no_of_views",
    "engagement"
]

# Make sure the rows still line up with the original dataframe
assert len(extra) == len(df), (
    f"ERROR: Row count mismatch. "
    f"df = {len(df):,}, extra = {len(extra):,}"
)

# Add the columns to our existing dataframe
for col in extra.columns:
    df[col] = extra[col].values

print()
print("Additional columns successfully added:")
print(extra.columns.tolist())


# ------------------------------------------------------------
# Select the columns we want in the final workbook
# ------------------------------------------------------------

output_columns = [
    "source",
    "content",
    "url",
    "domain",
    "topics",
    "sentiment",
    "sentiment class",
    "date (UTC)",
    "language",
    "no_of_comments",
    "no_of_likes",
    "no_of_shares",
    "no_of_views",
    "engagement",
    "hit_car_term",
    "hit_context_term",
    "step1_keep"
]


# ------------------------------------------------------------
# Separate Step 1 kept and removed rows
# ------------------------------------------------------------

step1_df = df.loc[
    df["step1_keep"],
    output_columns
].copy()

step1_removed_df = df.loc[
    ~df["step1_keep"],
    output_columns
].copy()


# ------------------------------------------------------------
# Save both into the SAME Excel workbook
# ------------------------------------------------------------

with pd.ExcelWriter(
    OUTPUT_PATH,
    engine="openpyxl"
) as writer:

    step1_df.to_excel(
        writer,
        sheet_name="Step1_Kept",
        index=False
    )

    step1_removed_df.to_excel(
        writer,
        sheet_name="Step1_Removed",
        index=False
    )


# ------------------------------------------------------------
# Final verification
# ------------------------------------------------------------

print()
print("=" * 70)
print("STEP 1 WORKBOOK CREATED")
print("=" * 70)

print(f"File: {OUTPUT_PATH}")
print(f"Step 1 kept    : {len(step1_df):,}")
print(f"Step 1 removed : {len(step1_removed_df):,}")
print(f"Total          : {len(step1_df) + len(step1_removed_df):,}")
print(f"Original df    : {len(df):,}")

assert (
    len(step1_df) + len(step1_removed_df)
    == len(df)
)

print()
print("Sheets:")
print("1. Step1_Kept")
print("2. Step1_Removed")
print()
print("✓ Complete.")

Original headers found:
['date (UTC)', 'language', 'no. of comments', 'no. of likes', 'no. of shares', 'no. of views', 'Engagements/social shares']

Additional columns successfully added:
['date (UTC)', 'language', 'no_of_comments', 'no_of_likes', 'no_of_shares', 'no_of_views', 'engagement']

======================================================================
STEP 1 WORKBOOK CREATED
======================================================================
File: step1_weak_filter.xlsx
Step 1 kept    : 55,005
Step 1 removed : 31,029
Total          : 86,034
Original df    : 86,034

Sheets:
1. Step1_Kept
2. Step1_Removed

✓ Complete.

In [21]:
# ============================================================
# DIAGNOSTIC — CHECK EXPLICIT CAR BRAND RETENTION
# ============================================================

brands_to_check = [
    "toyota",
    "proton",
    "honda",
    "perodua",
    "nissan",
    "mazda",
    "hyundai",
    "kia",
    "ford",
    "byd",
    "tesla",
    "chery",
    "bmw",
    "mercedes",
    "volkswagen",
    "audi"
]

print("=" * 70)
print("BRAND RETENTION AFTER STEP 1")
print("=" * 70)

for brand in brands_to_check:

    # Find rows containing the brand in the ORIGINAL content
    brand_in_original = (
        df["content"]
        .fillna("")
        .astype(str)
        .str.contains(
            rf"(?<!\w){brand}(?!\w)",
            case=False,
            regex=True
        )
    )

    total_brand = brand_in_original.sum()

    # Among those, how many survived Step 1?
    survived = (
        brand_in_original &
        df["step1_keep"]
    ).sum()

    removed = total_brand - survived

    print(
        f"{brand:15} "
        f"original: {total_brand:6,} | "
        f"kept: {survived:6,} | "
        f"removed: {removed:6,}"
    )

======================================================================
BRAND RETENTION AFTER STEP 1
======================================================================
toyota          original:    327 | kept:    327 | removed:      0
proton          original:    372 | kept:    372 | removed:      0
honda           original:    361 | kept:    361 | removed:      0
perodua         original:     49 | kept:     49 | removed:      0
nissan          original:     75 | kept:     75 | removed:      0
mazda           original:     97 | kept:     97 | removed:      0
hyundai         original:     52 | kept:     52 | removed:      0
kia             original:     45 | kept:     45 | removed:      0
ford            original:    328 | kept:    328 | removed:      0
byd             original:     58 | kept:     58 | removed:      0
tesla           original:    230 | kept:    230 | removed:      0
chery           original:     12 | kept:     12 | removed:      0
bmw             original:    184 | kept:    184 | removed:      0
mercedes        original:    118 | kept:    118 | removed:      0
volkswagen      original:     17 | kept:     17 | removed:      0
audi            original:     61 | kept:     61 | removed:      0